auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Yoite-Alice.tk
url: http://Yoite-Alice.tk
feed: /atom.xml
author_info: <a href="http://Yoite-Alice/">Yoite-Alice</a>
